export default {
  story: [""],
  // story: "",
  // storyTag: [],
  // question: "What is the most likely diagnosis in this case?",
  // question: "",
  question: [""],
  MCQs: [],
  questionSubmitForm: [],
  questionformchip: {},
  correctOptions: {},
  questionCategoryValue: [],
  // questionTagValueChange:[],
  questionTagsValue: [],
  selectedFeatures: [],
  // answers: ["option 1", "option 2", "option 3", "option 4", "option 5"],
  answers: {},
  data: [],
  answersData: [],
  // fields: { age: [5, 6, 7, 8], gender: ["male", "female"] },
  fields: {},
  tagfields: {},
  chiptagbtn: false,
  // categoriesFields: {},
  categoriesFields: [],
  categoriesInputVisible: true,
  // categoriesInputValue: ["male", "female"],
  inputVisible: {},
  inputValue: {},
  isGenerated: false,
  // correctAnswer: "Aspiration pneumonitis",
  questions: [
    {
      tagName: "firstTag",
      options: [
        {
          chipName: "age",
          options: ["jj", "kk", "ll"],
          selected: "jj",
        },
        {
          chipName: "color",
          options: ["jj", "kk", "ll"],
          selected: "ll",
        },
      ],
    },
    {
      tagName: "firstTag",
      options: [
        {
          chipName: "age",
          options: ["jj", "kk", "ll"],
          selected: "jj",
        },
        {
          chipName: "color",
          options: ["jj", "kk", "ll"],
          selected: "ll",
        },
      ],
    },
  ],
  genderSelect: ["Both", "Male", "Female"],
  }